version: '3'
services:
  telegram-client:
    build: ./telegram_webserver
    container_name: "telegram_client"
    ports:
      - "80:80"

  mongo-biblioteca:
    image: mongo
    container_name: mongo-biblioteca
    ports:
      - "27017:27017"
  pharo:
    image: dantebarba/pharo:40-slim
    container_name: pharo
    restart: always
    ports:
      - "8080:8080"
    command: pharo --no-xterm --headless /var/data/Pharo4.0.image st /var/data/run.st --no-quit
    volumes:
      - "./biblioteca_api:/var/data"
